"""empty message

Revision ID: 3c42da5c3ebd
Revises: 6947a9a074be
Create Date: 2023-08-15 21:19:03.296038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c42da5c3ebd'
down_revision = '6947a9a074be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_cards', schema=None) as batch_op:
        batch_op.drop_column('input_price')

    # ### end Alembic commands ###
