"""cards

Revision ID: de0094492745
Revises: 99adefe820c8
Create Date: 2023-08-15 05:06:19.833396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0094492745'
down_revision = '99adefe820c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('card_id_seq'::regclass)"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=40),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('card_id_seq'::regclass)"))

    # ### end Alembic commands ###
